// Countries that issue passports (ISO 3166-1 style, alphabetical)
window.COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
  'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Democratic Republic of the Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
  'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
  'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
  'Haiti', 'Honduras', 'Hungary',
  'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast',
  'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
  'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
  'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway',
  'Oman',
  'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar',
  'Romania', 'Russia', 'Rwanda',
  'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
  'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
  'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe'
];

// Visa types by country (destination country -> list of visa types)
// Common types used for many countries; country-specific where notable
window.VISA_TYPES_BY_COUNTRY = {
  'United States': ['B1/B2 Tourist', 'F1 Student', 'J1 Exchange', 'H1B Work', 'L1 Intracompany', 'O1 Extraordinary', 'K1 Fiancé(e)', 'Green Card / Immigrant', 'ESTA (VWP)', 'Transit C'],
  'United Kingdom': ['Standard Visitor', 'Skilled Worker', 'Student', 'High Potential Individual', 'Innovator', 'Start-up', 'Transit', 'EU Settlement'],
  'Canada': ['Visitor (Tourist)', 'Study Permit', 'Work Permit', 'Express Entry', 'Provincial Nominee', 'Super Visa', 'Transit', 'eTA'],
  'Australia': ['Visitor (600)', 'Student (500)', 'Skilled Independent (189)', 'Skilled Nominated (190)', 'Working Holiday', 'Partner', 'Transit', 'eVisitor / ETA'],
  'Schengen (EU)': ['Short-stay (C)', 'Long-stay (D)', 'Airport Transit (A)', 'Tourist', 'Business', 'Study', 'Work', 'Family Reunion'],
  'Germany': ['Schengen C', 'National D', 'Job Seeker', 'Work', 'Student', 'Family Reunion', 'Business'],
  'France': ['Schengen C', 'Long-stay D', 'Talent Passport', 'Student', 'Work', 'Visitor', 'Transit'],
  'Italy': ['Schengen C', 'National D', 'Work', 'Study', 'Elective Residence', 'Business'],
  'Spain': ['Schengen C', 'National D', 'Work', 'Study', 'Non-Lucrative', 'Golden Visa', 'Digital Nomad'],
  'Netherlands': ['Schengen C', 'MVV (Long-stay)', 'Work', 'Study', 'Highly Skilled', 'Start-up', 'Orientation Year'],
  'China': ['L Tourist', 'F Business', 'X1/X2 Student', 'Z Work', 'Q1/Q2 Family', 'M Commercial', 'Transit', '10-Year Visa'],
  'Japan': ['Temporary Visitor', 'Work', 'Student', 'Specified Skilled Worker', 'Business Manager', 'Highly Skilled Professional', 'Transit', 'Spouse/Child'],
  'India': ['Tourist (e-Visa)', 'Business', 'Employment', 'Student', 'Medical', 'Conference', 'Transit', 'OCI'],
  'Brazil': ['Visitor (VIVIS)', 'Work (VITEM V)', 'Student', 'Investor', 'Transit'],
  'Mexico': ['Visitor (FMM)', 'Temporary Resident', 'Permanent Resident', 'Work', 'Student', 'Investor'],
  'United Arab Emirates': ['Tourist', 'Visit', 'Work', 'Investor', 'Student', 'Transit', 'Golden Visa', 'Green Visa'],
  'Saudi Arabia': ['Tourist', 'Business', 'Work', 'Family Visit', 'Student', 'Transit', 'Umrah/Hajj'],
  'Singapore': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'Long-term Visit'],
  'South Korea': ['Short-term (C-3)', 'Work (E)', 'Student (D-2)', 'Working Holiday', 'Transit', 'K-ETA'],
  'New Zealand': ['Visitor', 'Student', 'Work', 'Working Holiday', 'Transit', 'NZeTA'],
  'South Africa': ['Visitor', 'Work', 'Study', 'Business', 'Transit', 'Critical Skills'],
  'Russia': ['Tourist', 'Business', 'Work', 'Student', 'Private', 'Transit'],
  'Turkey': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Thailand': ['Tourist', 'Non-Immigrant B (Work)', 'Non-Immigrant ED (Study)', 'Retirement', 'Elite', 'Transit'],
  'Vietnam': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Indonesia': ['Visit (VOA)', 'Business', 'Work', 'Student', 'Transit', 'e-VOA'],
  'Philippines': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'Balikbayan'],
  'Malaysia': ['Social Visit', 'Business', 'Work', 'Student', 'Transit', 'MM2H'],
  'Argentina': ['Tourist', 'Work', 'Student', 'Transit', 'Mercosur'],
  'Chile': ['Tourist', 'Work', 'Student', 'Transit', 'Temporary Residence'],
  'Colombia': ['Visitor', 'Work', 'Student', 'Investor', 'Transit'],
  'Egypt': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Israel': ['Tourist', 'Work', 'Student', 'Transit', 'A1/A5'],
  'Kenya': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Nigeria': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Pakistan': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Bangladesh': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Sri Lanka': ['Tourist', 'Business', 'Transit', 'e-Visa'],
  'Nepal': ['Tourist', 'Business', 'Transit', 'Visa on Arrival'],
  'Morocco': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Tunisia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Ghana': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Tanzania': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Uganda': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Ethiopia': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'South Sudan': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Rwanda': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Senegal': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Ivory Coast': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Cameroon': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Democratic Republic of the Congo': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Zambia': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Zimbabwe': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Botswana': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Namibia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Mozambique': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Angola': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Algeria': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Libya': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Sudan': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Iran': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Iraq': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Jordan': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Lebanon': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Kuwait': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Bahrain': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Qatar': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Oman': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Yemen': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Syria': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Afghanistan': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Kazakhstan': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Uzbekistan': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Turkmenistan': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Tajikistan': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Kyrgyzstan': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Azerbaijan': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Georgia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Armenia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Belarus': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Ukraine': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Moldova': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Albania': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'North Macedonia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Bosnia and Herzegovina': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Serbia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Montenegro': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Kosovo': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Poland': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Czech Republic': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Hungary': ['Schengen C', 'National D', 'Work', 'Study', 'Business', 'Golden Visa'],
  'Romania': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Bulgaria': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Greece': ['Schengen C', 'National D', 'Work', 'Study', 'Golden Visa'],
  'Croatia': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Slovenia': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Slovakia': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Austria': ['Schengen C', 'National D', 'Work', 'Study', 'Red-White-Red Card'],
  'Switzerland': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Belgium': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Portugal': ['Schengen C', 'National D', 'Work', 'Study', 'Golden Visa', 'D7', 'Digital Nomad'],
  'Ireland': ['Tourist', 'Work', 'Study', 'Business', 'Critical Skills'],
  'Sweden': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Norway': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Denmark': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Finland': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Iceland': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Estonia': ['Schengen C', 'National D', 'Work', 'Study', 'Digital Nomad'],
  'Latvia': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Lithuania': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Malta': ['Schengen C', 'National D', 'Work', 'Study', 'Golden Visa'],
  'Luxembourg': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Monaco': ['Schengen C', 'National D', 'Work', 'Study', 'Business'],
  'Andorra': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'San Marino': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Vatican City': ['Official', 'Tourist', 'Transit'],
  'Cyprus': ['Schengen C', 'National D', 'Work', 'Study', 'Golden Visa'],
  'Fiji': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Papua New Guinea': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Solomon Islands': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Vanuatu': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Samoa': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Tonga': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Kiribati': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Marshall Islands': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Micronesia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Palau': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Nauru': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Tuvalu': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Ecuador': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Peru': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Bolivia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Paraguay': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Uruguay': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Venezuela': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Guyana': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Suriname': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'e-Visa'],
  'Costa Rica': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Panama': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'Friendly Nations'],
  'Nicaragua': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Honduras': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'El Salvador': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Guatemala': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Belize': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Cuba': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Jamaica': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Haiti': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Dominican Republic': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Trinidad and Tobago': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Barbados': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Bahamas': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Antigua and Barbuda': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'Citizenship by Investment'],
  'Saint Kitts and Nevis': ['Tourist', 'Business', 'Work', 'Student', 'Transit', 'Citizenship by Investment'],
  'Saint Lucia': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Saint Vincent and the Grenadines': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Grenada': ['Tourist', 'Business', 'Work', 'Student', 'Transit'],
  'Dominica': ['Tourist', 'Business', 'Work', 'Student', 'Transit']
};

// Fill missing countries with common visa types
(function () {
  var common = ['Tourist', 'Business', 'Work', 'Student', 'Transit'];
  window.COUNTRIES.forEach(function (c) {
    if (!window.VISA_TYPES_BY_COUNTRY[c]) {
      window.VISA_TYPES_BY_COUNTRY[c] = common;
    }
  });
})();
